name: Linting with flake8

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8 linting
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Perform mandatory flake8 linting
        run: |
          pip3 install flake8
          flake8 --version
          flake8 . --show-source --statistics --count --ignore E231,E241,E501,E722,E741,F401,F403,F405,W503,W504

      - name: Perform optional exit-zero flake8 linting
        run: |
          flake8 . --exit-zero --statistics --count
